public interface SQLStatements {
	String PATRON_QUERY = "SELECT LOGINID FROM PATRON WHERE LOGINID = ? AND PASSWORD = ?";
	String LIBRARIAN_QUERY = "SELECT LOGINID FROM LIBRARIAN WHERE LOGINID = ?";
	String ACCESS_QUERY = "SELECT TRANSACCESS, PATRONACCESS, BOOKACCESS, LIBACCESS FROM LIBRARIAN WHERE LOGINID = ?";
}
