public interface SQLStatements {
	String PATRON_QUERY = "SELECT LOGINID FROM PATRON WHERE LOGINID = ? AND PASSWORD = ?";
	String LIBRARIAN_QUERY = "SELECT LOGINID FROM LIBRARIAN WHERE LOGINID = ?";
}
